#!/bin/bash

set -e

cd "$(dirname "$0")/.."

export DOTFILES=$(pwd -P)
TARGET=$HOME

DOTFILES_DIRS=$(ls -d $DOTFILES/*/ | awk -F "/" '{ print $(NF-1) }')

for F in $DOTFILES_DIRS ; do
  if [[ $F = "nvim" ]]; then
    echo "~ Installing :: $F"
    stow --dotfiles --dir $DOTFILES --target $TARGET $F
  fi

  if [[ $F = "tmux" ]]; then
    echo "~ Installing :: $F"
    stow --dotfiles --dir $DOTFILES --target $TARGET $F
  fi

  if [[ $F = "zsh" ]]; then
    echo "~ Installing :: $F"
    stow --dotfiles --dir $DOTFILES --target $TARGET $F
  fi

  # # Remove previous links
  # # NOTE: `stow` issues warning when working with absolute paths, so for now I am ignoring it
  # # GHI: https://github.com/aspiers/stow/issues/65
  # stow -D --dotfiles --dir $DOTFILES --target $TARGET $F 2>/dev/null

  # # Installed new links
done
